# This is a basic workflow to help you get started with Actions

name: CI-Development

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the development branch
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Development Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Defining the variables to re-use
    strategy:
      matrix:
        node_version: [14]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node_version }}
      
      - name: Run Linter
        run: |
          echo Running Linter for the React Client...
          cd client 
          npm install
          npm run start:lint
          
      - name: Run Formatter
        run: |
          echo Running Formatter for React Client...
          cd client
          npm install
          npm run start:formatting
      
      # Running, when linting was successful.
      - uses: actions/checkout@master
      - name: Merge development -> main
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: development
          target_branch: main
          github_token: ${{ github.token }}
